/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $getActivePage: typeof import('@nativescript/core')['$getActivePage']
  const $getRootFrame: typeof import('@nativescript/core')['$getRootFrame']
  const $navigateTo: typeof import('@nativescript/core')['$navigateTo']
  const AbsoluteLayout: typeof import('@nativescript/core')['AbsoluteLayout']
  const ActivityIndicator: typeof import('@nativescript/core')['ActivityIndicator']
  const Button: typeof import('@nativescript/core')['Button']
  const Color: typeof import('@nativescript/core')['Color']
  const CssProperty: typeof import('@nativescript/core')['CssProperty']
  const FlexboxLayout: typeof import('@nativescript/core')['FlexboxLayout']
  const Frame: typeof import('@nativescript/core')['Frame']
  const GridLayout: typeof import('@nativescript/core')['GridLayout']
  const Image: typeof import('@nativescript/core')['Image']
  const Label: typeof import('@nativescript/core')['Label']
  const NativeScriptVue: typeof import('nativescript-vue')['default']
  const Page: typeof import('@nativescript/core')['Page']
  const Progress: typeof import('@nativescript/core')['Progress']
  const ScrollView: typeof import('@nativescript/core')['ScrollView']
  const Slider: typeof import('@nativescript/core')['Slider']
  const StackLayout: typeof import('@nativescript/core')['StackLayout']
  const Style: typeof import('@nativescript/core')['Style']
  const StyleScope: typeof import('@nativescript/core')['StyleScope']
  const Switch: typeof import('@nativescript/core')['Switch']
  const TabView: typeof import('@nativescript/core')['TabView']
  const TabViewItem: typeof import('@nativescript/core')['TabViewItem']
  const TextField: typeof import('@nativescript/core')['TextField']
  const WrapLayout: typeof import('@nativescript/core')['WrapLayout']
  const computed: typeof import('nativescript-vue')['computed']
  const createApp: typeof import('nativescript-vue')['createApp']
  const onMounted: typeof import('nativescript-vue')['onMounted']
  const onShow: typeof import('nativescript-vue')['onShow']
  const onUnmounted: typeof import('nativescript-vue')['onUnmounted']
  const ref: typeof import('nativescript-vue')['ref']
  const registerElement: typeof import('nativescript-vue')['registerElement']
  const useAppLifecycleSync: typeof import('./app/composables/useAppLifecycleSync')['useAppLifecycleSync']
  const useRoute: typeof import('router-vue-native')['useRoute']
  const useRouter: typeof import('router-vue-native')['useRouter']
  const useTasksStore: typeof import('./app/store/tasks')['useTasksStore']
  const watch: typeof import('nativescript-vue')['watch']
  const watchEffect: typeof import('nativescript-vue')['watchEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Task } from './app/types/Task'
  import('./app/types/Task')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly $getActivePage: UnwrapRef<typeof import('@nativescript/core')['$getActivePage']>
    readonly $getRootFrame: UnwrapRef<typeof import('@nativescript/core')['$getRootFrame']>
    readonly $navigateTo: UnwrapRef<typeof import('@nativescript/core')['$navigateTo']>
    readonly AbsoluteLayout: UnwrapRef<typeof import('@nativescript/core')['AbsoluteLayout']>
    readonly ActivityIndicator: UnwrapRef<typeof import('@nativescript/core')['ActivityIndicator']>
    readonly Button: UnwrapRef<typeof import('@nativescript/core')['Button']>
    readonly Color: UnwrapRef<typeof import('@nativescript/core')['Color']>
    readonly CssProperty: UnwrapRef<typeof import('@nativescript/core')['CssProperty']>
    readonly FlexboxLayout: UnwrapRef<typeof import('@nativescript/core')['FlexboxLayout']>
    readonly Frame: UnwrapRef<typeof import('@nativescript/core')['Frame']>
    readonly GridLayout: UnwrapRef<typeof import('@nativescript/core')['GridLayout']>
    readonly Image: UnwrapRef<typeof import('@nativescript/core')['Image']>
    readonly Label: UnwrapRef<typeof import('@nativescript/core')['Label']>
    readonly NativeScriptVue: UnwrapRef<typeof import('nativescript-vue')['default']>
    readonly Page: UnwrapRef<typeof import('@nativescript/core')['Page']>
    readonly Progress: UnwrapRef<typeof import('@nativescript/core')['Progress']>
    readonly ScrollView: UnwrapRef<typeof import('@nativescript/core')['ScrollView']>
    readonly Slider: UnwrapRef<typeof import('@nativescript/core')['Slider']>
    readonly StackLayout: UnwrapRef<typeof import('@nativescript/core')['StackLayout']>
    readonly Style: UnwrapRef<typeof import('@nativescript/core')['Style']>
    readonly StyleScope: UnwrapRef<typeof import('@nativescript/core')['StyleScope']>
    readonly Switch: UnwrapRef<typeof import('@nativescript/core')['Switch']>
    readonly TabView: UnwrapRef<typeof import('@nativescript/core')['TabView']>
    readonly TabViewItem: UnwrapRef<typeof import('@nativescript/core')['TabViewItem']>
    readonly TextField: UnwrapRef<typeof import('@nativescript/core')['TextField']>
    readonly WrapLayout: UnwrapRef<typeof import('@nativescript/core')['WrapLayout']>
    readonly computed: UnwrapRef<typeof import('nativescript-vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('nativescript-vue')['createApp']>
    readonly onMounted: UnwrapRef<typeof import('nativescript-vue')['onMounted']>
    readonly onShow: UnwrapRef<typeof import('nativescript-vue')['onShow']>
    readonly onUnmounted: UnwrapRef<typeof import('nativescript-vue')['onUnmounted']>
    readonly ref: UnwrapRef<typeof import('nativescript-vue')['ref']>
    readonly registerElement: UnwrapRef<typeof import('nativescript-vue')['registerElement']>
    readonly useAppLifecycleSync: UnwrapRef<typeof import('./app/composables/useAppLifecycleSync')['useAppLifecycleSync']>
    readonly useRoute: UnwrapRef<typeof impo../app/composables/useAppLifecycleSync
    readonly useRouter: UnwrapRef<typeof import('router-vue-native')['useRouter']>
    readonly useTasksStore: UnwrapRef<typeof import('./app/store/tasks')['useTasksStore']>
    readonly watch: UnwrapRef<typeof import('nativescript-vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('nativescript-vue')['watchEffect']>
  }
}../app/store/tasks../app/types/Task../app/composables/useAppLifecycleSync../app/store/tasks
