/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $getActivePage: typeof import('@nativescript/core')['$getActivePage']
  const $getRootFrame: typeof import('@nativescript/core')['$getRootFrame']
  const $navigateBack: typeof import("@nativescript/core")["$navigateBack"]
  const $navigateTo: typeof import('@nativescript/core')['$navigateTo']
  const AbsoluteLayout: typeof import('@nativescript/core')['AbsoluteLayout']
  const ActivityIndicator: typeof import('@nativescript/core')['ActivityIndicator']
  const Button: typeof import('@nativescript/core')['Button']
  const Color: typeof import('@nativescript/core')['Color']
  const CssProperty: typeof import('@nativescript/core')['CssProperty']
  const EffectScope: typeof import("vue")["EffectScope"]
  const FlexboxLayout: typeof import('@nativescript/core')['FlexboxLayout']
  const Frame: typeof import('@nativescript/core')['Frame']
  const GridLayout: typeof import('@nativescript/core')['GridLayout']
  const Image: typeof import('@nativescript/core')['Image']
  const Label: typeof import('@nativescript/core')['Label']
  const NativeScriptVue: typeof import('nativescript-vue')['default']
  const Page: typeof import('@nativescript/core')['Page']
  const Progress: typeof import('@nativescript/core')['Progress']
  const SQL__delete: typeof import("./app/utils/sqlite_helper")["SQL__delete"]
  const SQL__dropTable: typeof import("./app/utils/sqlite_helper")["SQL__dropTable"]
  const SQL__insert: typeof import("./app/utils/sqlite_helper")["SQL__insert"]
  const SQL__query: typeof import("./app/utils/sqlite_helper")["SQL__query"]
  const SQL__select: typeof import("./app/utils/sqlite_helper")["SQL__select"]
  const SQL__selectRaw: typeof import("./app/utils/sqlite_helper")["SQL__selectRaw"]
  const SQL__truncate: typeof import("./app/utils/sqlite_helper")["SQL__truncate"]
  const SQL__update: typeof import("./app/utils/sqlite_helper")["SQL__update"]
  const ScrollView: typeof import('@nativescript/core')['ScrollView']
  const Slider: typeof import('@nativescript/core')['Slider']
  const StackLayout: typeof import('@nativescript/core')['StackLayout']
  const Style: typeof import('@nativescript/core')['Style']
  const StyleScope: typeof import('@nativescript/core')['StyleScope']
  const Switch: typeof import('@nativescript/core')['Switch']
  const TabView: typeof import('@nativescript/core')['TabView']
  const TabViewItem: typeof import('@nativescript/core')['TabViewItem']
  const TextField: typeof import('@nativescript/core')['TextField']
  const Vue: typeof import("nativescript-vue")["default"]
  const WrapLayout: typeof import('@nativescript/core')['WrapLayout']
  const betterFetch: typeof import('@better-fetch/fetch')['betterFetch']
  const computed: typeof import('nativescript-vue')['computed']
  const createApp: typeof import('nativescript-vue')['createApp']
  const createRouter: typeof import("@nativescript/vue-router")["createRouter"]
  const customRef: typeof import("vue")["customRef"]
  const defineAsyncComponent: typeof import("vue")["defineAsyncComponent"]
  const defineComponent: typeof import("vue")["defineComponent"]
  const effectScope: typeof import("vue")["effectScope"]
  const getCurrentInstance: typeof import("vue")["getCurrentInstance"]
  const getCurrentScope: typeof import("vue")["getCurrentScope"]
  const h: typeof import("vue")["h"]
  const initializeDatabase: typeof import("./app/utils/sqlite_helper")["initializeDatabase"]
  const inject: typeof import("vue")["inject"]
  const isProxy: typeof import("vue")["isProxy"]
  const isReactive: typeof import("vue")["isReactive"]
  const isReadonly: typeof import("vue")["isReadonly"]
  const isRef: typeof import("vue")["isRef"]
  const markRaw: typeof import("vue")["markRaw"]
  const nextTick: typeof import("vue")["nextTick"]
  const onActivated: typeof import("vue")["onActivated"]
  const onBeforeMount: typeof import("vue")["onBeforeMount"]
  const onBeforeUnmount: typeof import("vue")["onBeforeUnmount"]
  const onBeforeUpdate: typeof import("vue")["onBeforeUpdate"]
  const onDeactivated: typeof import("vue")["onDeactivated"]
  const onErrorCaptured: typeof import("vue")["onErrorCaptured"]
  const onMounted: typeof import('nativescript-vue')['onMounted']
  const onRenderTracked: typeof import("vue")["onRenderTracked"]
  const onRenderTriggered: typeof import("vue")["onRenderTriggered"]
  const onScopeDispose: typeof import("vue")["onScopeDispose"]
  const onServerPrefetch: typeof import("vue")["onServerPrefetch"]
  const onShow: typeof import('nativescript-vue')['onShow']
  const onUnmounted: typeof import('nativescript-vue')['onUnmounted']
  const onUpdated: typeof import("vue")["onUpdated"]
  const onWatcherCleanup: typeof import("vue")["onWatcherCleanup"]
  const provide: typeof import("vue")["provide"]
  const reactive: typeof import("vue")["reactive"]
  const readonly: typeof import("vue")["readonly"]
  const ref: typeof import('nativescript-vue')['ref']
  const registerElement: typeof import('nativescript-vue')['registerElement']
  const resolveComponent: typeof import("vue")["resolveComponent"]
  const shallowReactive: typeof import("vue")["shallowReactive"]
  const shallowReadonly: typeof import("vue")["shallowReadonly"]
  const shallowRef: typeof import("vue")["shallowRef"]
  const task: typeof import("./app/stores/useTasks")["default"]
  const toRaw: typeof import("vue")["toRaw"]
  const toRef: typeof import("vue")["toRef"]
  const toRefs: typeof import("vue")["toRefs"]
  const toValue: typeof import("vue")["toValue"]
  const triggerRef: typeof import("vue")["triggerRef"]
  const unref: typeof import("vue")["unref"]
  const useAppLifecycleSync: typeof import('../app/composables/useAppLifecycleSync')['useAppLifecycleSync']
  const useAttrs: typeof import("vue")["useAttrs"]
  const useCssModule: typeof import("vue")["useCssModule"]
  const useCssVars: typeof import("vue")["useCssVars"]
  const useId: typeof import("vue")["useId"]
  const useModel: typeof import("vue")["useModel"]
  const useRoute: typeof import('router-vue-native')['useRoute']
  const useRouter: typeof import('router-vue-native')['useRouter']
  const useSlots: typeof import("vue")["useSlots"]
  const useTasks: typeof import("./app/stores/useTasks")["default"]
  const useTasksStore: typeof import('../app/store/tasks')['useTasksStore']
  const useTemplateRef: typeof import("vue")["useTemplateRef"]
  const watch: typeof import('nativescript-vue')['watch']
  const watchEffect: typeof import('nativescript-vue')['watchEffect']
  const watchPostEffect: typeof import("vue")["watchPostEffect"]
  const watchSyncEffect: typeof import("vue")["watchSyncEffect"]
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Task } from '../app/types/Task'
  import('../app/types/Task')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly $getActivePage: UnwrapRef<typeof import('@nativescript/core')['$getActivePage']>
    readonly $getRootFrame: UnwrapRef<typeof import('@nativescript/core')['$getRootFrame']>
    readonly $navigateTo: UnwrapRef<typeof import('@nativescript/core')['$navigateTo']>
    readonly AbsoluteLayout: UnwrapRef<typeof import('@nativescript/core')['AbsoluteLayout']>
    readonly ActivityIndicator: UnwrapRef<typeof import('@nativescript/core')['ActivityIndicator']>
    readonly Button: UnwrapRef<typeof import('@nativescript/core')['Button']>
    readonly Color: UnwrapRef<typeof import('@nativescript/core')['Color']>
    readonly CssProperty: UnwrapRef<typeof import('@nativescript/core')['CssProperty']>
    readonly FlexboxLayout: UnwrapRef<typeof import('@nativescript/core')['FlexboxLayout']>
    readonly Frame: UnwrapRef<typeof import('@nativescript/core')['Frame']>
    readonly GridLayout: UnwrapRef<typeof import('@nativescript/core')['GridLayout']>
    readonly Image: UnwrapRef<typeof import('@nativescript/core')['Image']>
    readonly Label: UnwrapRef<typeof import('@nativescript/core')['Label']>
    readonly NativeScriptVue: UnwrapRef<typeof import('nativescript-vue')['default']>
    readonly Page: UnwrapRef<typeof import('@nativescript/core')['Page']>
    readonly Progress: UnwrapRef<typeof import('@nativescript/core')['Progress']>
    readonly ScrollView: UnwrapRef<typeof import('@nativescript/core')['ScrollView']>
    readonly Slider: UnwrapRef<typeof import('@nativescript/core')['Slider']>
    readonly StackLayout: UnwrapRef<typeof import('@nativescript/core')['StackLayout']>
    readonly Style: UnwrapRef<typeof import('@nativescript/core')['Style']>
    readonly StyleScope: UnwrapRef<typeof import('@nativescript/core')['StyleScope']>
    readonly Switch: UnwrapRef<typeof import('@nativescript/core')['Switch']>
    readonly TabView: UnwrapRef<typeof import('@nativescript/core')['TabView']>
    readonly TabViewItem: UnwrapRef<typeof import('@nativescript/core')['TabViewItem']>
    readonly TextField: UnwrapRef<typeof import('@nativescript/core')['TextField']>
    readonly WrapLayout: UnwrapRef<typeof import('@nativescript/core')['WrapLayout']>
    readonly betterFetch: UnwrapRef<typeof import('@better-fetch/fetch')['betterFetch']>
    readonly computed: UnwrapRef<typeof import('nativescript-vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('nativescript-vue')['createApp']>
    readonly onMounted: UnwrapRef<typeof import('nativescript-vue')['onMounted']>
    readonly onShow: UnwrapRef<typeof import('nativescript-vue')['onShow']>
    readonly onUnmounted: UnwrapRef<typeof import('nativescript-vue')['onUnmounted']>
    readonly ref: UnwrapRef<typeof import('nativescript-vue')['ref']>
    readonly registerElement: UnwrapRef<typeof import('nativescript-vue')['registerElement']>
    readonly useAppLifecycleSync: UnwrapRef<typeof import('../app/composables/useAppLifecycleSync')['useAppLifecycleSync']>
    readonly useRoute: UnwrapRef<typeof import('router-vue-native')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('router-vue-native')['useRouter']>
    readonly useTasksStore: UnwrapRef<typeof import('../app/store/tasks')['useTasksStore']>
    readonly watch: UnwrapRef<typeof import('nativescript-vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('nativescript-vue')['watchEffect']>
  }
}